add first hw
yanakhorolska/nodejs-rest-api pull request #1
Opened 2022-12-27 15:09 UTC by yanakhorolska

Please check my pull request

2022-12-27 16:27 UTC, KhYulian commented on models/contacts.js
> +  );
для отримання одного елементу з масиву використовуйте .find

2022-12-27 16:27 UTC, KhYulian commented on models/contacts.js
> +  return contactById;
Можна просто return contactById

2022-12-27 16:28 UTC, KhYulian commented on models/contacts.js
> +  await fs.writeFile(contactPath, JSON.stringify(contacts));
Якщо використовуєте async / await вже не використовуйте then

2022-12-27 16:28 UTC, KhYulian commented on models/contacts.js
> +  const index = contacts.findIndex((item) => item.id === contactId);
тут також краще використати .find

2022-12-27 16:29 UTC, KhYulian commented on routes/api/contacts.js
> +});
винесіть в окремий файл utils/validation/postContactValidationSchema або схожа назва

2022-12-27 16:31 UTC, KhYulian requested changes
Потрібно внести зміни відповідно до зауважень

2022-12-27 16:31 UTC, KhYulian commented
Також івдповідайте на коменти по мірі виправлення

2022-12-29 07:47 UTC, yanakhorolska commented on models/contacts.js
> +  );
Змінено

2022-12-29 07:48 UTC, yanakhorolska commented on models/contacts.js
> +  return contactById;
видалено зайвий тут if

2022-12-29 07:49 UTC, yanakhorolska commented on models/contacts.js
> +  await fs.writeFile(contactPath, JSON.stringify(contacts));
виправлено

2022-12-29 07:55 UTC, yanakhorolska commented on models/contacts.js
> +  const index = contacts.findIndex((item) => item.id === contactId);
виправлено

2022-12-29 08:00 UTC, yanakhorolska commented on routes/api/contacts.js
> +});
Схему винесено в окремий файл

2022-12-29 08:16 UTC, yanakhorolska commented
Прошу перевірити виправлення

2022-12-29 08:21 UTC, KhYulian approved these changes
Чудова робота :heart: :heart: :heart:

2022-12-29 08:22 UTC, merged