update hw-03
yanakhorolska/nodejs-rest-api pull request #2
Opened 2023-01-13 11:54 UTC by yanakhorolska

Доброго дня, прошу перевірити завдання з MongoDB

2023-01-13 12:20 UTC, KhYulian requested changes
Відповідайте на коменти по мірі виправлення :)

2023-01-13 12:20 UTC, KhYulian commented on utils/validation/postContactValidationSchema.js
> +  });
Винесіть const schema в окремий файл

2023-01-13 12:20 UTC, KhYulian commented on server.js
> +main();
Можна використати IIFE

2023-01-13 12:20 UTC, KhYulian commented on utils/validation/postContactValidationSchema.js
> +  });
аналогічно винесіть

2023-01-13 12:20 UTC, KhYulian commented on utils/validation/postContactValidationSchema.js
> +  });
також винесіть :)

2023-01-14 10:33 UTC, yanakhorolska commented on server.js
> +main();
виправлено

2023-01-14 11:47 UTC, yanakhorolska commented on utils/validation/postContactValidationSchema.js
> +  });
винесено в окремий файл

2023-01-14 11:48 UTC, yanakhorolska commented on utils/validation/postContactValidationSchema.js
> +  });
винесено в окремий файл

2023-01-14 11:48 UTC, yanakhorolska commented on utils/validation/postContactValidationSchema.js
> +  });
винесено в окремий файл

2023-01-14 13:23 UTC, KhYulian approved these changes
Чудова робота ❤️❤️

2023-01-14 13:23 UTC, merged